Add env processing and new labels
damieng/github-scripting pull request #2
Opened 2019-10-22 19:57 UTC by joshcanhelp

2019-10-22 22:19 UTC, damieng commented on pr-process/app.js
> +    { name: 'closed:stale', color: 'cfd3d7', description: 'Issue or PR has not seen activity recently' },
I wonder if we should have a separate file for which labels get created. I think Goalie is a bit specific to auth0 for this non-auth0 repo.

2019-10-22 22:19 UTC, damieng requested changes
Love the env var work... Need to remove goalie tho.  I think the CH ones are okay here.

2019-10-23 15:09 UTC, damieng commented
Merging for now to get us unblocked but need a more flexible way of customizing the labels.

2019-10-23 15:09 UTC, merged

2019-10-23 15:14 UTC, joshcanhelp commented
It's pretty flexible ... just drop an `additional-labels.js` in the same folder (which is ignored):

```js
module.exports = [
    { name: '[Goalie] Review Required', color: 'ccff00', description: 'Goalie triaged, ready for team review' }
];
```